default:
    trainer: ppo
    lambd: 0.95
    buffer_size: 25600
    batch_size: 3200
    num_epoch: 7
    learning_rate: 5e-4
    learning_rate_schedule: linear
    time_horizon: 2048
    epsilon: 0.3
    beta: 1e-2
    normalize: false
    num_layers: 2
    hidden_units: 128
    max_steps: 1.0e7
    summary_freq: 401
    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.99
    # Useless
    use_recurrent: false
    sequence_length: 0
    memory_size: 0

#Basic:
    # batch_size: 32
    # normalize: false
    # num_layers: 1
    # hidden_units: 20
    # beta: 5.0e-3
    # buffer_size: 256
    # max_steps: 5.0e5
    # summary_freq: 2000
    # time_horizon: 3
    # reward_signals:
        # extrinsic:
            # strength: 1.0
            # gamma: 0.9
